version: "2"
name: sambanova
distribution_spec:
  description: Use Sambanova for running LLM inference
  docker_image: null
  providers:
    inference:
      - remote::sambanova
    memory:
      - inline::faiss
    safety:
      - inline::llama-guard
    agents:
      - inline::meta-reference
    telemetry:
      - inline::meta-reference
image_type: conda
