name: local-tgi-conda-example
distribution_spec:
  distribution_type: local-plus-together-inference
  description: Use Together.ai for running LLM inference
  docker_image: null
  providers:
    inference: remote::together
    memory: meta-reference-faiss
    safety: meta-reference
    agentic_system: meta-reference
    telemetry: console
image_type: conda
