name: ollama
distribution_spec:
  description: Use ollama for running LLM inference
  providers:
    inference: remote::ollama
    memory:
    - inline::faiss
    - remote::chromadb
    - remote::pgvector
    safety: inline::llama-guard
    agents: inline::meta-reference
    telemetry: inline::meta-reference
