name: local-docker-example
distribution_spec:
  description: Use code from `llama_stack` itself to serve all llama stack APIs
  providers:
    inference: meta-reference
    memory: meta-reference-faiss
    safety: meta-reference
    agents: meta-reference
    telemetry: console
image_type: docker
