version: '2'
name: experimental-post-training
distribution_spec:
  description: Experimental template for post training
  docker_image: null
  providers:
    post_training:
    - inline::torchtune
    datasetio:
    - remote::huggingface
    inference:
    - inline::meta-reference
    memory:
    - inline::faiss
    - remote::chromadb
    - remote::pgvector
    safety:
    - inline::llama-guard
    agents:
    - inline::meta-reference
    telemetry:
    - inline::meta-reference
image_type: conda
