name: fireworks
distribution_spec:
  description: Use Fireworks.ai for running LLM inference
  providers:
    inference: remote::fireworks
    memory:
    - inline::faiss
    - remote::weaviate
    safety: inline::llama-guard
    agents: inline::meta-reference
    telemetry: inline::meta-reference
