services:
  llamastack:
    image: llamastack/fireworks
    ports:
      - "8321:8321"
    environment:
      - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
    entrypoint: bash -c "llama stack run fireworks"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
