name: bedrock
distribution_spec:
  description: Use Amazon Bedrock APIs.
  providers:
    inference: remote::bedrock
    memory: inline::faiss
    safety: inline::llama-guard
    agents: meta-reference
    telemetry: meta-reference
