name: together
distribution_spec:
  description: Use Together.ai for running LLM inference
  providers:
    inference: remote::together
    memory:
    - meta-reference
    - remote::weaviate
    safety: inline::llama-guard
    agents: meta-reference
    telemetry: meta-reference
