name: together
distribution_spec:
  description: Use Together.ai for running LLM inference
  providers:
    inference: remote::together
    memory:
    - meta-reference
    - remote::weaviate
    - remote::chromadb
    - remote::pgvector
    safety: remote::together
    agents: meta-reference
    telemetry: meta-reference
