name: together
distribution_spec:
  description: Use Together.ai for running LLM inference
  providers:
    inference: remote::together
    memory:
    - inline::faiss
    - remote::weaviate
    safety: inline::llama-guard
    agents: inline::meta-reference
    telemetry: inline::meta-reference
