name: Pull Request Labeler

on:
  pull_request_target:

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Labeler Action
      uses: actions/labeler@v5
