name: Docker Build and Publish

on:
  push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install llama-stack
        run: |
            pip install -e .

      - name: Build docker image
        run: |
          TEST_PYPI_VERSION=0.0.63.dev20250114 llama stack build --template ollama --image-type docker
          docker images

      - name: Push to dockerhub
        run: |
          docker tag distribution-ollama:0.0.63.dev20250114 llamastack/distribution-ollama:0.0.63.dev20250114
          docker push llamastack/distribution-ollama:0.0.63.dev20250114
