distribution_type: local-ollama
description: Like local, but use ollama for running LLM inference
docker_image: null
providers:
  inference: remote::ollama
  safety: meta-reference
  agentic_system: meta-reference
  memory: meta-reference-faiss
  telemetry: console
